#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changed_files=$(git diff --cached --name-only --diff-filter=ACM)

if echo "$changed_files" | grep -q '^src/'; then
  npx tsdx lint
fi

if echo "$changed_files" | grep -q '^docs/'; then
  cd docs && npm run lint
fi
